package pkg

import "text/template"

// 构造模板
func parseTemplateOrPanic(t string) *template.Template {
	tpl, err := template.New("output_template").Parse(t)
	if err != nil {
		panic(err)
	}
	return tpl
}

var outputTemplate = parseTemplateOrPanic(`
////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by genmodel, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package {{.PkgName}}

//go:generate gormgen -structs {{.StructName}} -input .
type {{.StructName}} struct {
{{range .Fields}}{{.FieldName}}		{{.FieldType}} ` + "`json:\"{{.ColumnName}}\"`" + `		//{{.ColumnComment}}
{{ end}}
}

func (_ *{{.StructName}}) TableName() string {
	return "{{.PkgName}}"
}
`)
