[Server]
cors = true
name = "Web-demo"
port = 8889

[mysql]
[mysql.read] # 从库信息，可读
addr = '127.0.0.1:3306' # MySQL 地址:端口
name = 'proxyapi' # 数据库名称
pass = '123456' # 密码
user = 'root' # 用户名
[mysql.write] # 主库信息，可读写
addr = '127.0.0.1:3306' # MySQL 地址:端口
name = 'proxyapi' # 数据库名称
pass = '123456' # 密码
user = 'root' # 用户名
[mysql.base] # 基础配置
connMaxLifeTime = 60 # 最大连接超时(单位:分)
maxIdleConn = 60 # 闲置的连接数
maxOpenConn = 10 # 最大打开的连接数

[jwt]
expireDuration = 12 # JWT ExpiresAt 过期时间(单位:小时)
secret = '21ddG1tdHyuJTrw7retY' # JWT secret
