////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by genmodel, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package orders

//go:generate gormgen -structs Order -input .
type Order struct {
	Id                     int32   `json:"id"`                        //
	OrderNo                string  `json:"order_no"`                  //订单号
	MemberId               int32   `json:"member_id"`                 //会员ID
	CompanyId              int32   `json:"company_id"`                //公司ID
	CustomerName           string  `json:"customer_name"`             //客户名称
	DeviceInfo             string  `json:"device_info"`               //下单设备
	ContractNo             string  `json:"contract_no"`               //商城服务费合同编号
	OfficialContractNo     string  `json:"official_contract_no"`      //商城官费合同编号
	CertificationId        int32   `json:"certification_id"`          //申请主体ID
	OrderSource            int32   `json:"order_source"`              //来源: 字典 order-source
	FileStatus             int32   `json:"file_status"`               //材料状态：字典 order-file_status
	PaymentStatus          int32   `json:"payment_status"`            //订单支付状态：字典order-payment_status
	PaymentChannelId       int32   `json:"payment_channel_id"`        //支付渠道表ID
	PaymentChannelType     int32   `json:"payment_channel_type"`      //支付渠道类型
	ContractStatus         int32   `json:"contract_status"`           //合同状态： 字典order-contract_status
	ContractSignedAt       int32   `json:"contract_signed_at"`        //合同签订时间
	Status                 int32   `json:"status"`                    //业务状态：字典 order-status
	IsClosed               int32   `json:"is_closed"`                 //是否已关闭
	IsPaid                 int32   `json:"is_paid"`                   //是否已支付
	Payable                float64 `json:"payable"`                   //应付金额
	PaymentNo              string  `json:"payment_no"`                //支付平台单号
	ActuallyPaid           float64 `json:"actually_paid"`             //实付金额
	BusinessAmount         int32   `json:"business_amount"`           //业务数量
	TotalAmount            float64 `json:"total_amount"`              //订单总金额
	TotalCost              float64 `json:"total_cost"`                //订单总成本
	PaidAt                 int32   `json:"paid_at"`                   //支付时间
	CityId                 int32   `json:"city_id"`                   //城市ID
	RefundStatus           int32   `json:"refund_status"`             //退款状态：字典 order_refund_status
	RefundNo               string  `json:"refund_no"`                 //退款单号
	Comment                string  `json:"comment"`                   //备注
	FinishedAt             int32   `json:"finished_at"`               //订单完成时间
	BiContractNo           string  `json:"bi_contract_no"`            //BI合同编号
	Recommender            string  `json:"recommender"`               //推荐人
	CashierUrl             string  `json:"cashier_url"`               //收银台地址
	Module                 string  `json:"module"`                    //模块：trademark、software、patent
	CurrentHandlerUserId   int32   `json:"current_handler_user_id"`   //当前操作人ID
	CurrentHandlerUserName string  `json:"current_handler_user_name"` //当前操作人姓名
	FileUploadTime         int32   `json:"file_upload_time"`          //材料上传时间
	FileApprovedTime       int32   `json:"file_approved_time"`        //材料审核通过时间
	FileGenReviewTime      int32   `json:"file_gen_review_time"`      //生成材料审核时间
	FileRejectRemark       string  `json:"file_reject_remark"`        //材料驳回原因
	ContactName            string  `json:"contact_name"`              //联系人姓名
	ContactMobile          string  `json:"contact_mobile"`            //联系人电话
	ContactEmail           string  `json:"contact_email"`             //联系人邮箱
	ContactTelephone       string  `json:"contact_telephone"`         //联系人座机
	ContactRemark          string  `json:"contact_remark"`            //联系人备注
	ContactAddress         string  `json:"contact_address"`           //联系人地址
	CreatedAt              int32   `json:"created_at"`                //创建时间
	UpdatedAt              int32   `json:"updated_at"`                //更新时间

}

func (_ *Order) TableName() string {
	return "orders"
}
